import { expect, test } from '@playwright/test';

/**
 * The point of the shadow root: the bar renders identically no matter what the
 * host page's CSS does. These fixtures each carry global styles chosen to break
 * a light-DOM header — an `a { color: red !important }`, a `button { all: unset }`,
 * Bootstrap 2's padding leak, Foundation's content-box reset.
 *
 * Every hostile fixture is measured against the same expectations as `bare`.
 */

const HOSTILE = ['bare', 'aggressive-reset', 'foundation'];

// The pixel-identity counterpart to these checks lives in tests/visual, so that
// every screenshot baseline is generated by the one containerized workflow.

/** Geometry + computed style of the pieces a host page would otherwise wreck. */
async function fingerprint(page: import('@playwright/test').Page) {
  return page.evaluate(() => {
    const root = document.getElementById('ucfhb')?.shadowRoot;
    if (!root) return null;
    const pick = (sel: string) => {
      const el = root.querySelector(sel);
      if (!el) return null;
      const r = el.getBoundingClientRect();
      const s = getComputedStyle(el);
      return {
        w: Math.round(r.width),
        h: Math.round(r.height),
        x: Math.round(r.x),
        color: s.color,
        background: s.backgroundColor,
        font: `${s.fontWeight} ${s.fontSize} ${s.textTransform}`,
      };
    };
    return {
      host: pick(':host') ?? null,
      bar: pick('.bar'),
      home: pick('.home'),
      mark: pick('.mark'),
      wordmark: pick('.wordmark'),
      toggle: pick('.search-toggle'),
      myucf: pick('.myucf'),
    };
  });
}

test.describe('shadow DOM isolation', () => {
  test('hostile host CSS cannot change the bar', async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 700 });

    await page.goto('/fixtures/bare.html');
    const baseline = await fingerprint(page);
    expect(baseline).not.toBeNull();

    for (const fixture of HOSTILE.slice(1)) {
      await page.goto(`/fixtures/${fixture}.html`);
      expect(await fingerprint(page), `${fixture} should match bare`).toEqual(baseline);
    }
  });

  // A host page whose <body> is padded insets the shadow host itself. The
  // shadow root cannot help: the host element's containing block is outside it.
  // Asserted so the limitation stays measured, and so a future fix has a test.
  test('KNOWN LIMITATION: a padded body still insets the bar', async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 700 });

    await page.goto('/fixtures/bare.html');
    const bare = await page.locator('#ucfhb').boundingBox();

    await page.goto('/fixtures/padded-body.html');
    const padded = await page.locator('#ucfhb').boundingBox();

    expect(padded?.x).toBe(20);
    expect(padded?.width).toBe((bare?.width ?? 0) - 40);
    // Everything inside the bar is still untouched — only its box moved.
    expect(padded?.height).toBe(bare?.height);
  });

  test('host page scripts cannot reach the internals', async ({ page }) => {
    await page.goto('/fixtures/bare.html');
    const leaked = await page.evaluate(() => ({
      byId: document.getElementById('ucfhb-q'),
      byClass: document.querySelector('.search-input'),
      byPart: document.querySelector('[part="bar"]'),
    }));
    expect(leaked.byId).toBeNull();
    expect(leaked.byClass).toBeNull();
    expect(leaked.byPart).toBeNull();
  });

  test('bar styles do not leak out onto the host page', async ({ page }) => {
    await page.goto('/fixtures/bare.html');
    const host = await page.evaluate(() => {
      const h1 = document.querySelector('.host-content h1');
      return h1 ? getComputedStyle(h1).textTransform : null;
    });
    expect(host).toBe('none');
  });
});

test.describe('theming API', () => {
  // The sanctioned replacement for reaching into the internals: custom
  // properties pierce the shadow boundary by design.
  test('custom properties set on #ucfhb do apply', async ({ page }) => {
    await page.goto('/fixtures/host-themed.html');
    const styles = await page.evaluate(() => {
      const root = document.getElementById('ucfhb')?.shadowRoot;
      const bar = root?.querySelector('.bar');
      const myucf = root?.querySelector('.myucf');
      return {
        bar: bar ? getComputedStyle(bar).backgroundColor : null,
        myucf: myucf ? getComputedStyle(myucf).backgroundColor : null,
      };
    });
    expect(styles.bar).toBe('rgb(26, 26, 26)');
    expect(styles.myucf).toBe('rgb(122, 184, 255)');
  });

  test('part= hooks are exposed for host-page styling', async ({ page }) => {
    await page.goto('/fixtures/bare.html');
    const parts = await page.evaluate(() => {
      const root = document.getElementById('ucfhb')?.shadowRoot;
      return [...(root?.querySelectorAll('[part]') ?? [])].map((e) => e.getAttribute('part'));
    });
    expect(parts).toEqual(expect.arrayContaining(['bar', 'logo', 'search', 'myucf']));
  });
});
