ContentsTree = new CTree("ContentsTree");
ContentsTree.bAutoClose = true;
ContentsTree.stTarget = "Main";
f1 = ContentsTree.AddNode(null, "General Statistics", "General_Statistics.htm");
ContentsTree.AddNode(f1, "Summary", "General_Statistics.htm#Summary");
f2 = ContentsTree.AddNode(null, "Activity Statistics", "Activity_Statistics.htm");
ContentsTree.AddNode(f2, "Daily", "Activity_Statistics.htm#Daily");
ContentsTree.AddNode(f2, "By Hour of Day", "Activity_Statistics.htm#By_Hour_of_Day");
f3 = ContentsTree.AddNode(null, "Access Statistics", "Access_Statistics.htm");
ContentsTree.AddNode(f3, "Pages", "Access_Statistics.htm#Pages");
ContentsTree.AddNode(f3, "Images", "Access_Statistics.htm#Images");
ContentsTree.AddNode(f3, "Directories", "Access_Statistics.htm#Directories");
ContentsTree.AddNode(f3, "Entry Pages", "Access_Statistics.htm#Entry_Pages");
f4 = ContentsTree.AddNode(null, "Visitors", "Visitors.htm");
ContentsTree.AddNode(f4, "Hosts", "Visitors.htm#Hosts");
f5 = ContentsTree.AddNode(null, "Referrers", "Referrers.htm");
ContentsTree.AddNode(f5, "Referring Sites", "Referrers.htm#Referring_Sites");
ContentsTree.AddNode(f5, "Referring URLs", "Referrers.htm#Referring_URLs");
ContentsTree.AddNode(f5, "Search Engines", "Referrers.htm#Search_Engines");
ContentsTree.AddNode(f5, "Search Phrases", "Referrers.htm#Search_Phrases");
f6 = ContentsTree.AddNode(null, "Browsers", "Browsers.htm");
ContentsTree.AddNode(f6, "Browsers", "Browsers.htm#Browsers");
ContentsTree.AddNode(f6, "Operating Systems", "Browsers.htm#Operating_Systems");
f7 = ContentsTree.AddNode(null, "Errors", "Errors.htm");
ContentsTree.AddNode(f7, "Types", "Errors.htm#Types");
document.write(ContentsTree.GetHTMLCode());