name: Azure Static Web Apps CI/CD LIVE

on:
  workflow_dispatch:
    inputs:
      manual_ref:
        type: string
        description: The tag or hash that needs to be deployed
        required: true

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
        GA: ${{ vars.GA_ID_LIVE }}
        ROOT_URL: ${{ vars.ROOT_URL_LIVE }}
        SEARCH_SERVICE: ${{ vars.SEARCH_SERVICE_URL_LIVE }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          ref: "${{ github.event.inputs.manual_ref }}"
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_MEADOW_084F3FA0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
